"""Messages changes

Revision ID: d30fa46ac928
Revises: 0388e8d5154e
Create Date: 2021-02-11 13:59:22.381281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30fa46ac928'
down_revision = '0388e8d5154e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.drop_column('message', 'author')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('message', sa.Column('author', sa.VARCHAR(length=40), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.alter_column('message', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
